### ISSUE TITLE
_X_AMZN_TRACE_ID is not set

### ISSUE THREAD

**Issue by PeterAdams-A** [swift-server/swift-aws-lambda-runtime#85]
The AWS guide - https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html - says a custom runtime should do the following

> **Propagate the tracing header** – Get the X-Ray tracing header from the Lambda-Runtime-Trace-Id header in the API response. Set the _X_AMZN_TRACE_ID environment variable locally with the same value. The X-Ray SDK uses this value to connect trace data between services.

The _X_AMZN_TRACE_ID environment variable is not currently set.

**Comment by Andrea-Scuderi** [comment]
It's required to trace the Lambda with X-ray according to the documentation: 
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html


> Propagate the tracing header – Get the X-Ray tracing header from the Lambda-Runtime-Trace-Id header in the API response. Set the _X_AMZN_TRACE_ID environment variable locally with the same value. The X-Ray SDK uses this value to connect trace data between services


I added it in my runtime to be able to evaluate the performances: https://github.com/swift-sprinter/aws-lambda-swift-sprinter-core/blob/master/Sources/LambdaSwiftSprinter/Sprinter.swift

The user can enable/disable it from the console so I think it should be set.

<img width="508" alt="Screenshot 2020-05-29 at 21 57 53" src="https://user-images.githubusercontent.com/8319309/83304953-b68e6200-a1f7-11ea-9cea-cb6b1eda6a81.png">

It's important to evaluate the performances:

<img width="1186" alt="Screenshot 2020-05-29 at 22 00 42" src="https://user-images.githubusercontent.com/8319309/83305064-ee95a500-a1f7-11ea-9e01-5a9aeeecd630.png">

**Comment by fabianfett** [comment]
Hi @Andrea-Scuderi, this runtime exposes the tracing header on the `Context` object for further context/trace propagation and in the logger as metadata for better log consolidation. If you enable tracing right now you will get an xray output just like you've shown above.

Since @bmoffatt has told us that we don't need to expose the header as an env variable I would argue to close this issue since it's original purpose doesn't need to be fulfilled. @tomerd wdyt?

**Comment by tomerd** [comment]
@bmoffatt is def the authority on this, so yes closing sgtm
